### ISSUE TITLE
Error building  flexcpp  with clang

### ISSUE THREAD

**Issue by slacka** [fbb-git/flexcpp#2]
Building  flexcpp  with clang results in:
`
./parser/parserbase.h:296:14: error: reference to non-static member function must be called; did you mean to call it with no arguments?`

The full log can be found here:
http://clang.debian.net/logs/2016-08-30/flexc++_2.05.00-1_unstable_clang.log

**Comment by fbb-git** [comment]
See the comparable issue with bisonc++: since I received no replies to the questions I asked there, and the issue reported here is identical to the one reported for bisonc++ I'm assuming this issue isn't relevant anymore, and therefore I'm closing it.
