### ISSUE TITLE
The current man page mentions 1.xx.xx has not been reached

### ISSUE THREAD

**Issue by louwers** [fbb-git/flexcpp#3]
From the current man page:

> By now, the project has evolved to a level that we feel it's defensible to publish the program, although we still tend to consider the program in its experimental stage; it will remain that way until we decide to move its version from the 0.9x.xx series to the 1.xx.xx series.

https://github.com/fbb-git/flexcpp/blob/master/flexc%2B%2B/documentation/man/flexc%2B%2B.yo

Since flexc++ is now production ready (right?), this sentence should definitely be replaced.

**Comment by fbb-git** [comment]
Dear Bart, you wrote:
> From the current man page:
> 
> > By now, the project has evolved to a level that we feel it's defensible to publish the program, although we still tend to consider the program in its experimental stage; it will remain that way until we decide to move its version from the 0.9x.xx series to the 1.xx.xx series.
>
https://github.com/fbb-git/flexcpp/blob/master/flexc%2B%2B/documentation/man/flexc%2B%2B.yo

Thx for your heads-up: I'll fix this in the next release.

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
