### ISSUE TITLE
Specification example will no longer compile

### ISSUE THREAD

**Issue by louwers** [fbb-git/flexcpp#4]
The specification example given in the flexc++input man page no longer compiles.
Presumably because the mini-scanners are now in a strongly typed enum. Hence if I am not mistaken

```
"/*"            begin(comment);

<comment>.|\n   // ignore
<comment>"*/"   begin(INITIAL);
```
needs to become

```
"/*"            begin(StartCondition__::comment);

<comment>.|\n   // ignore
<comment>"*/"   begin(StartCondition__::INITIAL);
 ```

Which is quite ugly, but that is another topic.

**Comment by fbb-git** [comment]
Dear Bart, you wrote:

> Presumably because the mini-scanners are now in a strongly typed enum. Hence
if I am not mistaken

You're right. Something else to fix. Thanks.
 
> Which is quite ugly, but that is another topic.

:-) There's no accounting for taste... 

Fortunately you don't have to look at it constantly :-)

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by louwers** [comment]
Very minor issue but there's also a stray `)` character at the end of that that section.

Closing this!
