### ISSUE TITLE
Problem with nested namespaces

### ISSUE THREAD

**Issue by avalchev** [fbb-git/flexcpp#8]
I have problems when using nested namespaces :)

This is my configuration:
```
%filenames = "MyParser"
%namespace = "my::nested::ns"
%class-name = "MyParser"
%baseclass-header = "MyParserBase.hpp"
%lex-source = "MyParserBase.cpp"
%class-header = "MyParser.hpp"
%implementation-header = "MyParserImpl.hpp"
%%
[ \t]+                              // skip white space chars.
[0-9]+                              return NUMBER;
[[:alpha:]_][[:alpha:][:digit:]_]*  return IDENTIFIER;
[][]                                return SIGNAL;
.                                   return matched()[0];
\n                                  begin(StartCondition__::INITIAL);
```

Here is the error:

```
In file included from parsing/flex/MyParserBase.cpp:9:
In file included from parsing/flex/MyParserImpl.hpp:4:
parsing/flex/MyParser.hpp:3:11: warning: extra tokens at end of #ifndef directive [-Wextra-tokens]
#ifndef my::nested::nsMyParser_H_INCLUDED_
          ^
          //
parsing/flex/MyParser.hpp:4:11: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define my::nested::nsMyParser_H_INCLUDED_
          ^

In file included from parsing/flex/MyParserBase.cpp:9:
In file included from parsing/flex/MyParserImpl.hpp:4:
In file included from parsing/flex/MyParser.hpp:7:
flex/MyParserBase.hpp:3:11: warning: extra tokens at end of #ifndef directive [-Wextra-tokens]
#ifndef my::nested::nsMyParserBASE_H_INCLUDED
          ^
          //
In file included from parsing/flex/MyParserBase.cpp:9:
In file included from parsing/flex/MyParserImpl.hpp:4:
parsing/flex/MyParser.hpp:10:11: error: expected identifier or '{'
namespace my::nested::ns
          ^
parsing/flex/MyParser.hpp:4:11: note: expanded from macro 'my'
#define my::nested::nsMyParser_H_INCLUDED_
          ^
parsing/flex/MyParser.hpp:10:11: error: no member named 'nested' in the global namespace
namespace my::nested::ns
          ^~
parsing/flex/MyParser.hpp:4:13: note: expanded from macro 'my'
#define my::nested::nsMyParser_H_INCLUDED_
          ~~^
parsing/flex/MyParserBase.cpp:12:11: error: expected identifier or '{'
namespace my::nested::ns
          ^
parsing/flex/MyParser.hpp:4:11: note: expanded from macro 'my'
#define my::nested::nsMyParser_H_INCLUDED_
          ^
parsing/flex/MyParserBase.cpp:12:11: error: no member named 'nested' in the global namespace
namespace my::nested::ns
          ^~
parsing/flex/MyParser.hpp:4:13: note: expanded from macro 'my'
#define my::nested::nsMyParser_H_INCLUDED_
```

When I replace `%namespace = "my::nested::ns"` whith `%namespace = "mynestedns"` everything works as expected. :)

I think that I'm using C++ feature for which flexc++ is not ready yet :)

**Comment by fbb-git** [comment]
Dear avalchev, you wrote:
> I have problems when using nested namespaces :)

Thanks for your report. It appears that you have a problem with the
preprocessor not accepting colons in defines ;-)

After removing the colons from the defines compilation got stuck on the
non-defined NUMBER, IDENTIFIER and SIGNAL, but that's of course as expected. 

In the meantime I suggest you find another temporary solution, maybe using a
namespace alias like

    namespace myNestedNs = my::nested::ns;

and then specify 

    %namespace myNestedNs

But it's likely that before this summer there will be a flexc++ upgrade. In
that new release I'll remove the colons from include-guard identifiers.

Thanks again!

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA

**Comment by avalchev** [comment]
Nested namespaces are not "showstopper" for for me... Just to report the problem :)

Expecting upgrade :)

**Comment by fbb-git** [comment]
Dear avalchev, you wrote:
> Nested namespaces are not "showstopper" for for me. 
> 
> Just to report the problem :)
> 
> Expecting upgrade :)

Good! Thanks for the feedback, though :-)

-- 
    Frank B. Brokken
    Center for Information Technology, University of Groningen
    (+31) 50 363 9281 
    Public PGP key: http://pgp.surfnet.nl
    Key Fingerprint: DF32 13DE B156 7732 E65E  3B4D 7DB2 A8BE EAE4 D8AA
