### ISSUE TITLE
Wrong use of [[fallthrough]] attribute in generated .cc

### ISSUE THREAD

**Issue by Clocktown** [fbb-git/flexcpp#9]
The Lexer implementation generated by flexcpp uses the `[[fallthrough]]` attribute in a wrong way. It should be followed by a semicolon, see e.g. [here](https://blog.tartanllama.xyz/c++17-attributes/) and [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0188r0.pdf).
E.g. currently, I have this:
```
size_t ScannerBase::Input::get()
{
    switch(size_t ch = next()) // get the next input char
    {
    case '\n':
        ++d_lineNr;
        [[fallthrough]]

    default:
        return ch;
    }
}
```
in my `lex.cc`, where it should be
```
size_t ScannerBase::Input::get()
{
    switch(size_t ch = next()) // get the next input char
    {
    case '\n':
        ++d_lineNr;
        [[fallthrough]]; // Semicolon needed!

    default:
        return ch;
    }
}
```

The Code is thus not conforming to the C++-17 standard. g++ ignores this, but Visual Studio won't compile this Code.

**Comment by fbb-git** [comment]
Nice! Thanks for the report. I'll fix that in the next release.

Btw, Flexc++'s `home' location has recently moved from github to gitlab. 
At gitlab the involved source files I already fixed the involved source files.
In the near future this will also be announced on the github site. Here's the
gitlab location:

    https://fbb-git.gitlab.io/flexcpp/

Cheers,
Frank.
